name: b11 deploy html to ec2

on:
  push:
    branches: 
    - main

jobs:
  deploy: 
    runs-on: ubantu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: List all the files
      run: ls -al
