on:

  push:

    branches:

      - main

      - dev

      - d

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code

        uses: actions/checkout@v4

      - name: Show all files

        run: ls -al
      - name: Execute remote SSH commands using password 
        uses: appleboy/ssh-action@v1 
        with: 
            host: ${{ secrets.HOST }} 
            username: linuxserver.io 
            password: ${{ secrets.PASSWORD }} 
            port: 22
            script: whoami
      - name: Copy file using scp
        uses: appleboy/ssh-action@v1 
        with: 
            host: ${{ secrets.HOST }} 
            username: linuxserver.io 
            password: ${{ secrets.PASSWORD }} 
            port: 22
            script: whoami
